export const adminContent = {
  auth: {
    eyebrow: "Panel privado",
    headerText: "Acceso reservado para revisar y organizar las confirmaciones.",
    loginTitle: "Acceso admin",
    loginText: "Introduce la contraseña para entrar al panel de gestión.",
    passwordLabel: "Contraseña",
    passwordPlaceholder: "Contraseña privada",
    submit: "Entrar",
    backHome: "Volver al inicio",
    loading: "Cargando datos...",
    error: "La contraseña no es correcta.",
  },
  stats: {
    header: {
      eyebrow: "Panel privado",
      title: "Resumen",
      text: "Seguimiento de respuestas recibidas y datos operativos",
    },
    confirmations: {
      eyebrow: "Confirmaciones",
      title: "Confirmaciones",
      charts: {
        allergies: "Alergias",
        transport: "Transporte",
        transportTitle: "Autobús",
        outbound: "Ida",
        return: "Vuelta",
      },
    },
    providers: {
      eyebrow: "Proveedores",
      title: "Proveedores",
    },
    tables: {
      eyebrow: "Mesas y asientos",
      title: "Mesas y asientos",
    },
    notifications: {
      eyebrow: "Notificaciones",
      title: "Notificaciones",
    },
    dialogs: {
      warningEyebrow: "Aviso",
      problemTitle: "Ha ocurrido un problema",
      loadError:
        "No se pudieron cargar las estadísticas. Revisa que el endpoint admin devuelva el listado de confirmaciones.",
    },
  },
  guests: {
    tabs: [
      { id: "confirmations", label: "Confirmaciones" },
      { id: "guests", label: "Invitados" },
    ],
    header: {
      eyebrow: "Panel privado",
      title: "Lista de invitados",
      text: "Gestión de confirmaciones, datos de contacto, alergias y transporte",
    },
    overview: {
      eyebrow: "Confirmaciones",
      title: "Confirmaciones",
      metrics: {
        confirmations: "Recibidas",
        guests: "Invitados",
        meat: "Carne",
        fish: "Pescado",
        allergies: "Alergias",
        otherAllergies: "Otras",
        comments: "Notas",
        outboundBus: "Ida",
        returnBus: "Vuelta",
      },
    },
    filters: {
      eyebrow: "Filtros",
      searchLabel: "Busqueda",
      searchPlaceholder: "Email, teléfono, grupo, nombre o apellidos",
      showLabel: "Mostrar",
      options: [
        { value: "all", label: "Todos" },
        { value: "allergies", label: "Con alergias" },
        { value: "bus", label: "Con bus" },
        { value: "comments", label: "Con notas" },
      ],
    },
    list: {
      eyebrow: "Gestión de confirmaciones",
      title: "Gestión de confirmaciones",
      pageLabel: "Confirmación",
      mobilePageLabel: "Confirmación",
      emptyTitle: "Sin resultados",
      emptyText: "Prueba con otra búsqueda o cambia el filtro seleccionado.",
      noConfirmationsTitle: "Sin confirmaciones",
      noConfirmationsText:
        "Crea una confirmación para empezar a registrar invitados.",
      countLabel: ({ confirmations, guests }) =>
        `${confirmations} ${confirmations === 1 ? "confirmación" : "confirmaciones"} en esta página · ${guests} ${
          guests === 1 ? "persona" : "personas"
        }`,
    },
    editor: {
      guestListEyebrow: "Lista de invitados",
      guestListTitle: "Invitados",
      guestCountLabel: ({ page, total }) => `${page} / ${total}`,
    },
    guestList: {
      eyebrow: "Invitados confirmados",
      title: "Invitados confirmados",
      mobilePageLabel: "Invitado",
      noConfirmationsTitle: "Sin confirmaciones",
      noConfirmationsText:
        "Crea una confirmación antes de agregar o consultar invitados.",
      noGuestsTitle: "Sin invitados",
      noGuestsText:
        "La confirmación seleccionada todavia no tiene invitados registrados.",
      noSelectionTitle: "Selecciona una confirmación",
      noSelectionText:
        "Elige una confirmación en el tab principal para gestionar sus invitados.",
      noFilterText:
        "No hay invitados que coincidan con la busqueda o el filtro seleccionado.",
    },
    actions: {
      discardChanges: "Deshacer cambios",
      export: "Exportar",
      refresh: "Actualizar",
      saveChanges: "Guardar cambios",
      create: "Crear",
      edit: "Editar",
      editGuests: "Editar invitados",
      delete: "Eliminar",
    },
    dialogs: {
      groupCreateTitle: "Crear confirmación",
      groupEditorTitle: "Editar confirmación",
      guestEditorTitle: "Editar invitado",
      guestListEditorTitle: "Editar invitados",
      unsavedTitle: "Se perderan los cambios",
      unsavedMessage:
        "Tienes cambios sin guardar en esta confirmacion. Si sales ahora, se perderan.",
      unsavedText:
        "Tienes cambios pendientes en invitados. Si sales ahora, no se enviaran a Apps Script.",
      keepEditing: "Seguir editando",
      exitWithoutSaving: "Salir sin guardar",
      saveAndExit: "Guardar y salir",
      discardChanges: "Salir sin guardar",
      validationTitle: "Revisa la confirmación",
      validationMessage:
        "Hay campos obligatorios o con formato incorrecto. Corrigelos antes de guardar la confirmacion.",
      deleteTitle: "Eliminar confirmación",
      deleteMessage: (label) =>
        `Se marcará para eliminar la confirmación asociada a ${label}. Podrás deshacerlo antes de guardar los cambios.`,
      guestDeleteTitle: "Eliminar invitado",
      guestDeleteMessage: (label) =>
        `Se marcará para eliminar a ${label}. Podrás deshacerlo antes de guardar los cambios.`,
      loadError:
        "No se pudieron cargar los invitados. Revisa que el endpoint admin devuelva el listado de confirmaciones.",
      saveError:
        "No se ha podido guardar la confirmación. Revisa los datos e inténtalo de nuevo.",
      deleteError:
        "No se ha podido eliminar la confirmación. Inténtalo de nuevo en unos minutos.",
      createdTitle: "Confirmación creada",
      updatedTitle: "Cambios guardados",
      deletedTitle: "Confirmación eliminada",
      pendingTitle: "Cambios pendientes",
      createdMessage: "La confirmación se ha creado correctamente.",
      updatedMessage: "La confirmación se ha actualizado correctamente.",
      deletedMessage: "La confirmación se ha eliminado correctamente.",
      pendingMessage:
        "Los cambios se han aplicado en memoria. Usa Guardar cambios para enviarlos.",
      successEyebrow: "Confirmación",
      warningEyebrow: "Aviso",
      problemTitle: "Ha ocurrido un problema",
      close: "Cerrar",
    },
    spinner: {
      create: "Creando confirmación...",
      save: "Guardando confirmación...",
      saveChanges: "Guardando cambios...",
      delete: "Eliminando confirmación...",
    },
    csv: {
      filename: "grupos-invitados.csv",
      headers: [
        "email",
        "telefono",
        "nombre_grupo",
        "total_invitados",
        "mesa_menu_asiento",
        "alergias",
        "transporte",
        "notas",
      ],
    },
  },
  tables: {
    tabs: [
      { id: "tables", label: "Mesas" },
      { id: "pending", label: "Pendientes" },
    ],
    header: {
      adminEyebrow: "Panel privado",
      title: "Mesas",
      text: "Organización de mesas, asientos e invitados asignados.",
      eyebrow: "Gestión de mesas",
      sectionTitle: "Gestión de mesas",
      exportTable: "Exportar tabla",
      pageLabel: "Pagina",
      mobilePageLabel: "Mesas",
      tableCountLabel: ({ seats, tables }) =>
        `${tables} ${tables === 1 ? "mesa" : "mesas"} en esta pagina - ${seats} ${
          seats === 1 ? "asiento" : "asientos"
        }`,
      pendingGuestCountLabel: (count) =>
        `${count} ${count === 1 ? "invitado pendiente" : "invitados pendientes"}`,
    },
    actions: {
      sectionEyebrow: "Acciones",
      addTable: "Agregar mesa",
      saveChanges: "Guardar cambios",
      discardChanges: "Deshacer cambios",
      editTable: "Editar mesa",
      deleteTable: "Eliminar mesa",
    },
    empty: {
      title: "Sin mesas",
      text: "Crea una mesa para empezar a distribuir invitados y asientos.",
    },
    dialogs: {
      createTitle: "Crear mesa",
      editTitle: "Editar mesa",
      deleteTitle: "Eliminar mesa",
      deleteMessage: (tableName) =>
        `¿Estás seguro que deseas eliminar la mesa ${tableName}? Esta acción liberará cualquier asiento asignado a esta mesa.`,
      assignmentTitle: "Asignar invitado",
      guestLabel: "Invitado",
      guestPlaceholder: "Seleccionar invitado",
      currentGuest: (guestName) => `Asignado a ${guestName}.`,
      assignedTitle: "Asignados",
      unassignedTitle: "Sin asientos asignados",
      unassignedText: "No hay invitados asignados a esta mesa.",
      unassignSeat: "Liberar asiento",
      unassigningSeat: "Liberando...",
      unassignSeatTitle: "Liberar asiento",
      unassignSeatMessage: (guestName, tableName, seatNumber) =>
        `Se liberara el asiento ${seatNumber} de la mesa ${tableName} asignado a ${guestName}. Esta accion no se puede deshacer desde este panel.`,
      remove: "Eliminar",
      assign: "Asignar invitado",
      assigning: "Asignando...",
      cancel: "Cancelar",
      close: "Cerrar",
      unsavedEyebrow: "Cambios sin guardar",
      unsavedTitle: "Se perderan los cambios",
      unsavedText:
        "Tienes cambios pendientes en mesas. Si sales ahora, no se enviaran a Apps Script.",
      keepEditing: "Seguir editando",
      exitWithoutSaving: "Salir sin guardar",
      saveAndExit: "Guardar y salir",
      problemTitle: "Ha ocurrido un problema",
      warningEyebrow: "Aviso",
    },
    overview: {
      eyebrow: "Mesas y asientos",
      title: "Mesas y asientos",
      metrics: {
        tableCount: "Mesas",
        tables: "Mesas",
        seatCount: "Asientos",
        seats: "Asientos",
        assignedSeats: "Asignados",
        assigned: "Asignados",
        pendingSeats: "Pendientes",
        pending: "Pendientes",
      },
    },
    spinner: {
      save: "Guardando cambios...",
    },
    errors: {
      load: "No se pudieron cargar las mesas. Revisa que el endpoint admin devuelva el listado de confirmaciones.",
      save: "No se pudieron guardar los cambios. Intenta de nuevo.",
      assign: "No se pudo asignar el asiento. Intenta de nuevo.",
      assignTable: "No se pudo asignar la mesa. Intenta de nuevo.",
      unassign: "No se pudo liberar el asiento. Intenta de nuevo.",
    },
    changes: {
      created: (name) => `Mesa creada: ${name}`,
      modified: (name) => `Mesa modificada: ${name}`,
      deleted: (name) => `Mesa eliminada: ${name}`,
      noSeat: "Sin asiento",
      assignmentLabel: ({ table, seat }) =>
        `Mesa ${table || "-"}, asiento ${seat || "-"}`,
    },
  },
  providers: {
    tabs: [
      { id: "providers", label: "Proveedores" },
      { id: "services", label: "Servicios" },
    ],
    header: {
      eyebrow: "Panel privado",
      title: "Proveedores",
      text: "Gestión de proveedores, servicios contratados y plazos de pago.",
    },
    overview: {
      eyebrow: "Proveedores",
      title: "Proveedores",
      metrics: {
        providers: "Proveedores",
        services: "Servicios",
        categories: "Categorías",
        budget: "Presupuesto",
        paid: "Pagado",
        pending: "Pendiente",
        nextPayments: "Próximos",
        nextPaymentDate: "Fecha",
        nextPaymentAmount: "Importe",
        paidServices: "Servicios pagados",
      },
    },
    list: {
      eyebrow: "Gestión de proveedores",
      title: "Gestión de proveedores",
      pageLabel: "Proveedores",
      mobilePageLabel: "Proveedores",
      emptyTitle: "Sin proveedores",
      emptyText: "Agrega proveedores para comenzar a organizar el presupuesto.",
      noFilterText:
        "No hay proveedores que coincidan con la busqueda o la categoria seleccionada.",
    },
    services: {
      eyebrow: "Servicios del proveedor",
      title: "Servicios del proveedor",
      pageLabel: "Servicios",
      mobilePageLabel: "Servicios",
      emptyTitle: "Sin servicios",
      emptyText: "Agrega servicios dentro de un proveedor para verlos aquí.",
      noProvidersTitle: "Sin proveedores",
      noProvidersText:
        "Crea un proveedor antes de agregar o consultar servicios.",
      noSelectionTitle: "Selecciona un proveedor",
      noSelectionText:
        "Elige un proveedor en el tab principal para gestionar sus servicios.",
      noFilterText:
        "No hay servicios que coincidan con la busqueda o la categoria seleccionada.",
    },
    filters: {
      eyebrow: "Filtros",
      searchLabel: "Búsqueda",
      searchPlaceholder: "Nombre, email, teléfono, servicio o categoría",
      categoryLabel: "Categoría",
      allCategories: "Todas",
      paymentStatusLabel: "Pago",
      allPaymentStatuses: "Todos",
      paymentStatuses: [
        { value: "paid", label: "Pagado" },
        { value: "unpaid", label: "No pagado" },
      ],
    },
    actions: {
      add: "Agregar proveedor",
      delete: "Eliminar",
      discardChanges: "Deshacer cambios",
      edit: "Editar",
      export: "Exportar",
      saveChanges: "Guardar cambios",
    },
    dialogs: {
      createTitle: "Crear proveedor",
      editTitle: "Editar proveedor",
      createServiceTitle: "Crear servicio",
      editServiceTitle: "Editar servicio",
      deleteTitle: "Eliminar proveedor",
      deleteMessage: (name) =>
        `Se marcará para eliminar el proveedor ${name}. Podrás deshacerlo antes de guardar los cambios.`,
      problemTitle: "Ha ocurrido un problema",
      deleteServiceTitle: "Eliminar servicio",
      deleteServiceMessage: (name) =>
        `Se marcará para eliminar el servicio ${name}. Podrás deshacerlo antes de guardar los cambios.`,
      loadError: "No se pudieron cargar los proveedores.",
      saveError: "No se pudieron guardar los proveedores.",
      unsavedText:
        "Tienes cambios pendientes en proveedores. Si sales ahora, no se guardarán.",
      warningEyebrow: "Aviso",
    },
    form: {
      contactTitle: "Datos del proveedor",
      servicesTitle: "Servicios",
      addService: "Agregar servicio",
      deleteService: "Eliminar servicio",
      save: "Guardar proveedor",
      fields: {
        accountNumber: "Número de cuenta",
        address: "Dirección",
        category: "Categoría",
        email: "Email",
        name: "Nombre",
        phone: "Teléfono",
        serviceName: "Servicio",
        paymentCount: "Plazos",
        servicePrice: "Precio",
        web: "Web",
      },
      payment: (index) => `Plazo ${index}`,
    },
    spinner: {
      load: "Cargando proveedores...",
      save: "Guardando proveedores...",
    },
  },
  notifications: {
    header: {
      eyebrow: "Panel privado",
      title: "Notificaciones",
      text: "Avisos internos, pagos y confirmaciones pendientes de revisar.",
    },
    access: {
      empty: "No hay notificaciones pendientes.",
      label: "Abrir notificaciones",
      shortLabel: "Avisos",
      viewAll: "Ver notificaciones",
    },
    overview: {
      eyebrow: "Notificaciones",
      title: "Notificaciones",
      metrics: {
        total: "Total",
        read: "Leídas",
        unread: "No leídas",
        warning: "Avisos",
        payment: "Pagos",
        confirmation: "Cambios",
      },
    },
    form: {
      eyebrow: "Crear",
      title: "Notificación",
      save: "Guardar notificación",
      fields: {
        date: "Fecha",
        detail: "Detalle",
        title: "Título",
        type: "Tipo",
      },
      placeholders: {
        detail: "Detalle opcional",
        title: "Ej: Pago pendiente del fotógrafo",
      },
    },
    filters: {
      eyebrow: "Filtros",
      searchLabel: "Búsqueda",
      searchPlaceholder: "Título, detalle, tipo o fecha",
      typeLabel: "Tipo",
      allTypes: "Todos",
      readLabel: "Estado",
    },
    list: {
      eyebrow: "Gestión de notificaciones",
      title: "Gestión de notificaciones",
      pageLabel: "Notificaciones",
      mobilePageLabel: "Notificaciones",
      emptyTitle: "Sin notificaciones",
      emptyText: "Crea una notificación para verla en este listado.",
    },
    actions: {
      create: "Agregar",
      delete: "Eliminar",
      discardChanges: "Deshacer cambios",
      markRead: "Marcar como leída",
    },
    dialogs: {
      createTitle: "Crear notificación",
      deleteMessage: (title) =>
        `Se marcará para eliminar la notificación ${title}. Podrás deshacerlo antes de guardar los cambios.`,
      deleteTitle: "Eliminar notificación",
      discardTitle: "Deshacer cambios de notificaciones",
      discardText: "Se desharán los cambios pendientes de notificaciones.",
      editTitle: "Editar notificación",
      loadError: "No se pudieron cargar las notificaciones.",
      problemTitle: "Ha ocurrido un problema",
      unsavedTitle: "Cambios pendientes",
      unsavedText:
        "Tienes cambios pendientes en notificaciones. Si sales ahora, no se guardarán.",
      warningEyebrow: "Aviso",
    },
  },
  pendingGuests: {
    filtersEyebrow: "Filtros",
    title: "Invitados pendientes",
    confirmationLabel: "Confirmación",
    allConfirmations: "Todas las confirmaciones",
    menuLabel: "Preferencia de menú",
    allMenus: "Todos los menús",
    emptyTitle: "Sin invitados pendientes",
    emptyText: "Todos los invitados confirmados tienen mesa asignada.",
    noTablesTitle: "Sin mesas",
    noTablesText:
      "Crea al menos una mesa antes de asignar invitados pendientes.",
    noFilterResults: "No hay invitados que coincidan con los filtros.",
    pageLabel: ({ page, total }) => `${page} / ${total}`,
    showingLabel: ({ filtered, total }) =>
      `Mostrando ${filtered} de ${total} invitados pendientes`,
    pendingEyebrow: "Invitados pendientes",
    tableLabel: "Mesa",
    tablePlaceholder: "Seleccionar",
    selectTableFirst: "Selecciona una mesa",
    seatLabel: "Asiento",
    seatOption: (seat) => `Asiento ${seat}`,
    previous: "Anterior",
    next: "Siguiente",
    assign: "Asignar",
    assigning: "Asignando...",
    emptySeatsLabel: (count) => `${count} asientos libres`,
  },
};
